### PR TITLE
New progress bar with estimated remaining time.

### PR DESCRIPTION
**Pull request by zzawadz**
I love your package. It's very helpful, but I have always missed one functionality - printing of estimated remaining time.

So I have added new, custom progress bar to your package with this time estimation:
```r
pbreplicate(1000, Sys.sleep(runif(1, 0.01)))
# |+++                                                                           | 2.70% ~09m 05s
pbreplicate(100000, Sys.sleep(runif(1, 0.1)))
# |+                                                                               | 0.02% ~13h 08m 28s   

```

I hope it will be usefull:)

```r
pb = startpb(max = 100)
 # |                                                                                  | 0.00% ~~calculating  
  pb()
 # |+                                                                                | 1.00% ~00s
```

### CODE REVIEW

**Comment by psolymos** [comment]
Thanks @zzawadz ! It looks like a cool and useful feature. I'll review it shortly. I am not sure that I will change the default option though.

**Comment by psolymos** [comment]
OK, so it works and does the job right, thanks. I called it 'timer' instead of 'custom' and is still the default because I think it is neat. I did some timings and couldn't detect any noticeable overhead due to extra calculations and string processing.

I'd like to follow the functions `getTxtProgressBar`, `setTxtProgressBar`, and `txtProgressBar` more closely, so that the timer functionality works outside of the `pbapply` functions. Something like adding `getTimerProgressBar`, `setTimerProgressBar`, and `timerProgressBar`.

**Comment by zzawadz** [comment]
Ok. I'll rewrite it for this *progressBar* scheme:)

**Comment by psolymos** [comment]
I already had a look and the best way is probably have elapsed time (since start time) stored with the value, so that the `get*` function can retrieve it, and just have it printed. I couldn't finish last night, but based on what you already had it seemed quite doable.

I was also thinking about replacing the progress bar (`|+++++     |`) with a **throbber**. For example the following characters would replace each other: `|/-\-`. This would indicate that calculations are ongoing, while the time estimate would give an idea of how long. Again, named as `throbberProgressBar` or something.

**Comment by zzawadz** [comment]
Ok. But if you want, I can do this for you tomorrow:) 

Maybe we should pack this progress bar in reference class, or sth similar to it?

**Comment by psolymos** [comment]
What do you mean by reference class?

I can wait a day or two so that you can write it up :) I'll have you then as package author if you are OK with that.

**Comment by zzawadz** [comment]
I thought about R RefClass (http://www.inside-r.org/r-doc/methods/referenceclasses), but I looked at the implementation of txtProgressBar, and changed my mind.

Now there is a function called timerProgressBar - and it has similar interface as txtProgressBar. So similar that setTimerProgressBar, and getTimerProgresBar are just:
```r
setTimerProgressBar <- setTxtProgressBar
getTimerProgressBar <- getTxtProgressBar
```
timerProgressBar inherits from txtProgressBar:)

I think it is more consistent.

**Comment by psolymos** [comment]
Merged the PR, thanks for the nice contribution (check out authors field in DESCRIPTION). 

Note: 

* I added couple of more arguments 
* defined `.killed` for `close`ing the connection
* exported the new functions,
* wrote Rd file.

**Comment by zzawadz** [comment]
Thanks:)

**Comment by psolymos** [comment]
Version 1.2-0 is CRAN now and tagged: https://github.com/psolymos/pbapply/releases/tag/v1.2-0

**Pull request merged**
